# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ayatool.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(314, 421)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget_6 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 281, 31))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.hboxProfile = QtGui.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.hboxProfile.setMargin(0)
        self.hboxProfile.setObjectName(_fromUtf8("hboxProfile"))
        self.comboProfile = QtGui.QComboBox(self.horizontalLayoutWidget_6)
        self.comboProfile.setObjectName(_fromUtf8("comboProfile"))
        self.comboProfile.addItem(_fromUtf8(""))
        self.comboProfile.addItem(_fromUtf8(""))
        self.comboProfile.addItem(_fromUtf8(""))
        self.comboProfile.addItem(_fromUtf8(""))
        self.comboProfile.addItem(_fromUtf8(""))
        self.hboxProfile.addWidget(self.comboProfile)
        self.hboxProfile.setStretch(0, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 281, 121))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 261, 31))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.hboxLedMode = QtGui.QHBoxLayout(self.layoutWidget)
        self.hboxLedMode.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.hboxLedMode.setMargin(0)
        self.hboxLedMode.setSpacing(6)
        self.hboxLedMode.setObjectName(_fromUtf8("hboxLedMode"))
        self.radioLedOff = QtGui.QRadioButton(self.layoutWidget)
        self.radioLedOff.setChecked(True)
        self.radioLedOff.setObjectName(_fromUtf8("radioLedOff"))
        self.hboxLedMode.addWidget(self.radioLedOff)
        self.radioLedOn = QtGui.QRadioButton(self.layoutWidget)
        self.radioLedOn.setObjectName(_fromUtf8("radioLedOn"))
        self.hboxLedMode.addWidget(self.radioLedOn)
        self.radioLedBreathe = QtGui.QRadioButton(self.layoutWidget)
        self.radioLedBreathe.setObjectName(_fromUtf8("radioLedBreathe"))
        self.hboxLedMode.addWidget(self.radioLedBreathe)
        self.radioLedCycle = QtGui.QRadioButton(self.layoutWidget)
        self.radioLedCycle.setObjectName(_fromUtf8("radioLedCycle"))
        self.hboxLedMode.addWidget(self.radioLedCycle)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.groupBox)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 261, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.hboxLedColor = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hboxLedColor.setMargin(0)
        self.hboxLedColor.setObjectName(_fromUtf8("hboxLedColor"))
        self.labelColor = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.labelColor.setObjectName(_fromUtf8("labelColor"))
        self.hboxLedColor.addWidget(self.labelColor)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 180, 281, 111))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 70, 261, 31))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.hboxSmartKey = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.hboxSmartKey.setMargin(0)
        self.hboxSmartKey.setObjectName(_fromUtf8("hboxSmartKey"))
        self.labelSmartKey = QtGui.QLabel(self.horizontalLayoutWidget_5)
        self.labelSmartKey.setObjectName(_fromUtf8("labelSmartKey"))
        self.hboxSmartKey.addWidget(self.labelSmartKey)
        self.comboSmartKey = QtGui.QComboBox(self.horizontalLayoutWidget_5)
        self.comboSmartKey.setObjectName(_fromUtf8("comboSmartKey"))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.comboSmartKey.addItem(_fromUtf8(""))
        self.hboxSmartKey.addWidget(self.comboSmartKey)
        self.hboxSmartKey.setStretch(0, 1)
        self.hboxSmartKey.setStretch(1, 1)
        self.horizontalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 261, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.hboxMousePolling = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.hboxMousePolling.setMargin(0)
        self.hboxMousePolling.setObjectName(_fromUtf8("hboxMousePolling"))
        self.labelMousePolling = QtGui.QLabel(self.horizontalLayoutWidget)
        self.labelMousePolling.setObjectName(_fromUtf8("labelMousePolling"))
        self.hboxMousePolling.addWidget(self.labelMousePolling)
        self.comboMousePolling = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.comboMousePolling.setObjectName(_fromUtf8("comboMousePolling"))
        self.comboMousePolling.addItem(_fromUtf8(""))
        self.comboMousePolling.addItem(_fromUtf8(""))
        self.comboMousePolling.addItem(_fromUtf8(""))
        self.comboMousePolling.addItem(_fromUtf8(""))
        self.hboxMousePolling.addWidget(self.comboMousePolling)
        self.hboxMousePolling.setStretch(0, 1)
        self.hboxMousePolling.setStretch(1, 1)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 310, 261, 31))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnApply = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.btnApply.setObjectName(_fromUtf8("btnApply"))
        self.horizontalLayout.addWidget(self.btnApply)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 314, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.btnAbout = QtGui.QAction(MainWindow)
        self.btnAbout.setObjectName(_fromUtf8("btnAbout"))
        self.btnUpdateMouse = QtGui.QAction(MainWindow)
        self.btnUpdateMouse.setObjectName(_fromUtf8("btnUpdateMouse"))
        self.btnFactoryReset = QtGui.QAction(MainWindow)
        self.btnFactoryReset.setObjectName(_fromUtf8("btnFactoryReset"))
        self.btnExit = QtGui.QAction(MainWindow)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.btnGithub = QtGui.QAction(MainWindow)
        self.btnGithub.setObjectName(_fromUtf8("btnGithub"))
        self.menuFile.addAction(self.btnUpdateMouse)
        self.menuFile.addAction(self.btnFactoryReset)
        self.menuFile.addAction(self.btnExit)
        self.menuHelp.addAction(self.btnGithub)
        self.menuHelp.addAction(self.btnAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "AYA Mouse Tool", None))
        self.comboProfile.setItemText(0, _translate("MainWindow", "Profile Slot 1", None))
        self.comboProfile.setItemText(1, _translate("MainWindow", "Profile Slot 2", None))
        self.comboProfile.setItemText(2, _translate("MainWindow", "Profile Slot 3", None))
        self.comboProfile.setItemText(3, _translate("MainWindow", "Profile Slot 4", None))
        self.comboProfile.setItemText(4, _translate("MainWindow", "Profile Slot 5", None))
        self.groupBox.setTitle(_translate("MainWindow", "LED Control", None))
        self.radioLedOff.setText(_translate("MainWindow", "Off", None))
        self.radioLedOn.setText(_translate("MainWindow", "On", None))
        self.radioLedBreathe.setText(_translate("MainWindow", "Breathe", None))
        self.radioLedCycle.setText(_translate("MainWindow", "Cycle", None))
        self.labelColor.setText(_translate("MainWindow", "Change Color", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mouse Settings", None))
        self.labelSmartKey.setText(_translate("MainWindow", "Smart Key", None))
        self.comboSmartKey.setItemText(0, _translate("MainWindow", "20ms", None))
        self.comboSmartKey.setItemText(1, _translate("MainWindow", "40ms", None))
        self.comboSmartKey.setItemText(2, _translate("MainWindow", "60ms", None))
        self.comboSmartKey.setItemText(3, _translate("MainWindow", "80ms", None))
        self.comboSmartKey.setItemText(4, _translate("MainWindow", "100ms", None))
        self.comboSmartKey.setItemText(5, _translate("MainWindow", "120ms", None))
        self.comboSmartKey.setItemText(6, _translate("MainWindow", "140ms", None))
        self.comboSmartKey.setItemText(7, _translate("MainWindow", "160ms", None))
        self.comboSmartKey.setItemText(8, _translate("MainWindow", "180ms", None))
        self.comboSmartKey.setItemText(9, _translate("MainWindow", "200ms", None))
        self.comboSmartKey.setItemText(10, _translate("MainWindow", "220ms", None))
        self.comboSmartKey.setItemText(11, _translate("MainWindow", "240ms", None))
        self.labelMousePolling.setText(_translate("MainWindow", "Polling Rate", None))
        self.comboMousePolling.setItemText(0, _translate("MainWindow", "125hz", None))
        self.comboMousePolling.setItemText(1, _translate("MainWindow", "250hz", None))
        self.comboMousePolling.setItemText(2, _translate("MainWindow", "500hz", None))
        self.comboMousePolling.setItemText(3, _translate("MainWindow", "1000hz", None))
        self.btnApply.setText(_translate("MainWindow", "Apply", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.btnAbout.setText(_translate("MainWindow", "About", None))
        self.btnUpdateMouse.setText(_translate("MainWindow", "Update Mouse", None))
        self.btnFactoryReset.setText(_translate("MainWindow", "Factory Reset", None))
        self.btnExit.setText(_translate("MainWindow", "Exit", None))
        self.btnGithub.setText(_translate("MainWindow", "Github Page", None))

